version: "2.2"
services:
  jd-seckill:
    container_name: jd-seckill
    image: jd-seckill:latest
    build:
      context: ../dockerfile
      dockerfile: Dockerfile
    env_file:
      - ../dockerfile/docker.env
